### ISSUE TITLE
Have to update config.json everyday

### ISSUE THREAD

**Issue by murphmr** [graanco/homebridge-SimpliSafePlatform#7]
For some reason with version 22 I have to update my config.json every day to put the simplisafe password back in.

**Comment by graanco** [comment]
I get the same thing I will update the code today

**Comment by graanco** [comment]
Wait... it seems to have stop the refresh token is working now.... How about you?

**Comment by graanco** [comment]
I updated the code... maybe now?

**Comment by carlmiller99** [comment]
Hmmmm... I dont see any errors but homebridge is unresponsive in home.app since updating to 1.0.23. Anyone else have it working?

**Comment by graanco** [comment]
I'll look at the code maybe I left the websocket running

**Comment by graanco** [comment]
I see you did a reset for the accessories.. are you fixed now?

**Comment by carlmiller99** [comment]
No unfortunately I have only had "No Response" ever since 1.0.23.  I just updated to 25, no change.

I tried killing the process and staying logged out for 2 hours, timer set to 60, no change.

I don't see errors in the output stream, but I do see this in my error log:

0|homebrid | (node:1543) [DEP0112] DeprecationWarning: Socket.prototype._handle is deprecated
0|homebrid | (node:765) [DEP0112] DeprecationWarning: Socket.prototype._handle is deprecated
0|homebrid | (node:776) [DEP0112] DeprecationWarning: Socket.prototype._handle is deprecated
0|homebrid | (node:761) [DEP0112] DeprecationWarning: Socket.prototype._handle is deprecated
0|homebrid | (node:767) [DEP0112] DeprecationWarning: Socket.prototype._handle is deprecated

**Comment by carlmiller99** [comment]
murphmr have you gotten it working since the updates? i seem to be stuck with homebridge nonresponsvie / undiscoverable

**Comment by graanco** [comment]
I would go and reset home ridge back to defaults... and configure the confit with password...

**Comment by carlmiller99** [comment]
I removed homebridge, deleted /persist/, repaired homebridge to home.app and am now back up on 1.0.26. Thank you!

**Comment by graanco** [comment]
okay I think I am going to remove SS2 or less support... The delay is causing a response issue. Also I will be setting it up so there is a 30 second loop for the alarm status unless I can get the push working from socket.io

**Comment by graanco** [comment]
No more changing... went back to the original code...
